export const notFound = require("../assets/icons/not-found.png")
export const check = require("../assets/icons/check.png")
export const add = require("../assets/icons/add.png")
export const humidity = require('../assets/icons/humidity.png')
export const air_humidity = require('../assets/icons/air_humidity.png')
export const temperature = require('../assets/icons/temperature.png')
export const tank = require('../assets/icons/tank.png')
export const user = require('../assets/users/profile.png')